version: '3'
services:
  chat-backend:
    build: chat-backend-grpc
    ports:
      - 26565:6565
    networks:
      - envoymesh

  chat-webapp:
    build: chat-webapp
    depends_on:
      - chat-backend
      - chat-proxy
    ports:
      - 24200:4200
    networks:
      - envoymesh
    volumes:
      - ./chat-webapp:/usr/src/app:rw
      - /usr/src/app/node_modules

  chat-proxy:
    image: envoyproxy/envoy-alpine
    environment:
      NODE_ENV: development
    ports:
      - 28080:8080
      - 28081:8081
    networks:
      - envoymesh
    volumes:
      - ./chat-proxy/envoy.yaml:/etc/envoy/envoy.yaml

networks:
  envoymesh: {}
